[project]
name = "agentic-and-generative-ai"
version = "0.1.0"
description = "Agentic & Generative Ai"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-google-genai>=2.0.9",
    "langgraph>=0.2.70",
    "python-dotenv>=1.0.1",
]
